INSERT INTO ACCESO_USUARIO(id_acceso, nombre_acceso) VALUES (1, 'Usuario');
INSERT INTO ACCESO_USUARIO(id_acceso, nombre_acceso) VALUES (2, 'Administrador');

INSERT INTO ESTADO_USUARIO(id_estado, nombre_estado) VALUES (0, 'PENDIENTE');
INSERT INTO ESTADO_USUARIO(id_estado, nombre_estado) VALUES (1, 'VALIDADO');
INSERT INTO ESTADO_USUARIO(id_estado, nombre_estado) VALUES (2, 'RECHAZADO');

INSERT INTO TIPO_COMPETICION(id_tipo_competicion, nombre_tipo_competicion) VALUES (1, 'Liga');
INSERT INTO TIPO_COMPETICION(id_tipo_competicion, nombre_tipo_competicion) VALUES (2, 'Copa');
INSERT INTO TIPO_COMPETICION(id_tipo_competicion, nombre_tipo_competicion) VALUES (3, 'Mixto');

INSERT INTO TIPO_JORNADA(id_tipo_jornada, nombre_tipo_jornada) VALUES (1, 'Liga');
INSERT INTO TIPO_JORNADA(id_tipo_jornada, nombre_tipo_jornada) VALUES (2, 'Eliminatoria');

INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Beira R&iacute;o", "Porto Alegre");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Estadio Castel&atilde;o", "Fortaleza");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Arena Fonte Nova", "Salvador de Bah&iacute;a");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Estadio Mineirao", "Belo Horizonte");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Estadio Nacional", "Brasilia");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Estadio Das Dunas", "Natal");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Estadio Maracan&aacute;", "R&iacute;o de Janeiro");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Arena da Baixada", "Curitiba");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Arena Pantanal", "Cuiab&aacute;");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Arena de S&atilde;o Paulo", "S&atilde;o Paulo");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Arena de Pernambuco", "Recife");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Arena Amazonia", "Manaos");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Juegos Mediterr&aacute;neos", "Almer&iacute;");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("San Mam&eacute;s", "Bilbao");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Vicente Calder&oacute;n", "Madrid");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Camp Nou", "Barcelona");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Bala&iacute;dos", "Vigo");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Nuevo Arc&aacute;ngel", "C&oacute;rdoba");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Riazor", "La Coruña");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Ipur&uacute;a", "Eibar");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Mart&iacute;nez Valero", "Elche");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Montjuic", "Barcelona");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Alfonso P&eacute;rez", "Getafe");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Nuevo Los C&aacute;rmenes", "Granada");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Ciutat de Valencia", "Valencia");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("La Rosaleda", "M&aacute;laga");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Santiago Bernab&eacute;u", "Madrid");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Anoeta", "San Sebasti&aacute;n");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Vallecas", "Madrid");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("S&aacute;nchez Pizju&aacute;n", "Sevilla");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Mestalla", "Valencia");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("El Madrigal", "Villarreal");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("El Molinon", "Gijón");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Benito Villamar&iacute;n", "Sevilla");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Insular", "Las Palmas de Gran Canaria");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Stade de France", "Saint-Denis");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Parc des Princes", "París");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Stade de Lyon", "Lyon");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Stade Velodrome", "Marsella");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Stade Pierre-Mauroy", "Lille");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Stade Bollaert-Delelis", "Lens");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Stade de Bordeaux", "Burdeos");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Stade Geoffroy-Guichard", "Saint-Etienne");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Stade de Toulouse", "Toulouse");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Stade de Nice", "Niza");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Mendizorroza", "Vitoria");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("Butarque", "Leganés");
INSERT INTO ESTADIOS(nombre_estadio, ciudad) VALUES ("El Sadar", "Pamplona");